# Generated by Django 3.0.5 on 2023-05-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='アーティスト')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='フォルダ名')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='ユーザー名')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=20, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=30, verbose_name='曲名')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Artist')),
            ],
            options={
                'unique_together': {('artist', 'song')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ファイル名')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.Folder', verbose_name='フォルダ')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dt', models.DateField(verbose_name='参戦日')),
                ('plase', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('artist', models.ManyToManyField(to='diary.Artist', verbose_name='アーティスト')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.File', verbose_name='フォルダ')),
                ('setlist', models.ManyToManyField(to='diary.Setlist', verbose_name='曲名')),
            ],
        ),
    ]
