# Generated by Django 4.2.2 on 2023-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_delete_user_remove_diary_file_diary_folder_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='setlist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Setlist',
        ),
        migrations.AddField(
            model_name='diary',
            name='artist',
            field=models.CharField(max_length=20, null=True, verbose_name='アーティスト'),
        ),
        migrations.AddField(
            model_name='diary',
            name='setlist',
            field=models.CharField(max_length=20, null=True, verbose_name='セットリスト'),
        ),
    ]
