# Generated by Django 4.2.2 on 2023-06-24 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_setlist_unique_together_remove_setlist_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='アーティスト')),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='diary.diary')),
            ],
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=30, verbose_name='曲名')),
                ('artist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='diary.artist')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
