# Generated by Django 4.2.2 on 2023-06-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_rename_diary_entry_artist_diary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='latest_diary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.artist'),
        ),
    ]
