# Generated by Django 4.2.2 on 2023-06-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_folder_latest_diary_date_alter_setlist_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='latest_diary_date',
        ),
    ]
