# Generated by Django 4.2.2 on 2023-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_folder_latest_diary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='folder',
        ),
        migrations.AddField(
            model_name='diary',
            name='folder',
            field=models.ManyToManyField(to='diary.folder', verbose_name='フォルダ'),
        ),
    ]
