# Generated by Django 4.2.2 on 2023-07-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_remove_diary_folder_diary_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='setlist',
        ),
    ]
