# Generated by Django 4.2.2 on 2023-08-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_remove_diary_artist_remove_diary_setlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='plase',
            new_name='place',
        ),
    ]
